# Shared ZoKrates pipeline for the demos in this folder.
#
# Each demo's Makefile sets any knobs it needs and then includes this file.
# The contract is:
#   main.zok    the circuit (checked in, or generated by helper.py)
#   inputs.txt  one line: the space-separated arguments for main
#
# Arguments go in via --stdin rather than -a: large_hash passes thousands of
# bytes, which would not fit on a command line.

ZOKRATES ?= zokrates
PYTHON   ?= python3

# `decode` caps how many list entries land in the JSON: the sha256 circuits have
# one proving-key point per wire, so an uncapped dump is tens of MB. The decode
# itself is always complete -- only the output is shortened. DECODE_MAX=0 dumps
# everything.
DECODE_MAX ?= 64

# Directory of this file, so demos can live anywhere under demos/.
UTILS := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))utils)

.PHONY: all compile setup prove verify decode clean
.DEFAULT_GOAL := verify

all: verify

## compile -- circuit -> constraint system (out, out.r1cs, abi.json)
compile: out

# `&:` marks these as one recipe producing all three, so make runs it once.
out out.r1cs abi.json &: main.zok
	$(ZOKRATES) compile -i main.zok -o out

## setup -- Groth16 keypair for this constraint system
setup: proving.key

proving.key verification.key &: out
	$(ZOKRATES) setup -i out

# The witness is a real file, so make can skip recomputing it.
witness out.wtns &: out inputs.txt
	$(ZOKRATES) compute-witness -i out --stdin < inputs.txt

## prove -- witness + proving key -> proof.json
prove: proof.json

proof.json: out proving.key witness
	$(ZOKRATES) generate-proof -i out

## verify -- check proof.json against verification.key
verify: proof.json verification.key
	$(ZOKRATES) verify

## decode -- deserialize the binary artifacts into *.decoded.json
decode: out out.r1cs witness out.wtns proving.key verification.key
	$(PYTHON) $(UTILS)/inspect_artifacts.py . --max $(DECODE_MAX)
	$(PYTHON) $(UTILS)/inspect_pk.py . --max $(DECODE_MAX)

## clean -- remove every generated file
clean:
	rm -f out out.r1cs out.wtns abi.json witness \
	      proving.key verification.key proof.json \
	      inputs.txt *.decoded.json
